### ISSUE TITLE
SX: generated classes inside media queries

### ISSUE THREAD

**Issue by michalsanger** [adeira/universe#1090]
```js
const styles = sx.create({
  style1: {
    "@media (min-width: 1280px)": {
      color: "red"
    },
    color: "blue"
  },
  style2: {
    color: "red"
  }
});

function Example() {
  return (
    <>
      <div className={styles('style1')}>Red on big screen, blue otherwise</div>
      <div className={styles('style2')}>Always red</div>
    </>
  )
}
```

Does not work as expected because of the generated stylesheet:

```css
@media (min-width: 640px) {
  .wUqnh.wUqnh {
    color: #f00;
  }
}
._4fo5TC {
  color: #00f;
}
.wUqnh {
  color: #f00;
}
```

`_4fo5TC` (blue) is never used. 

Instead of `.wUqnh.wUqnh` we probably should generate different hashes for styles inside media query.
